version: '3'
services:
  web-server: 
    image: nginx
    volumes:
      - ../frontend/:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    network_mode: host
  landing-page:
    image: app-tunnel
    entrypoint: lt --port 80 --subdomain 'ifiver'
    restart: unless-stopped
    network_mode: host
  dashboard:
    image: app-tunnel
    entrypoint: lt --port 9869 --subdomain 'dashboard-ifiver'
    restart: unless-stopped
    network_mode: host
  backend:
    image: app-tunnel
    entrypoint: lt --port 8080 --subdomain 'api-ifiver'
    restart: unless-stopped
    network_mode: host
  backend-server:
    image: app-api
    restart: unless-stopped
    expose:
      - 8080
