version: '3.5'
services:
  web-server: 
    image: nginx
    volumes:
      - ../frontend/:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    network_mode: host
    depends_on:
      - api-server
  api-server:
    image: app-api
    restart: unless-stopped
    network_mode: host
    expose:
      - 8080
  landing-page:
    image: app-tunnel
    entrypoint: lt --port 80 --subdomain 'ifiver'
    restart: unless-stopped
    network_mode: host
    depends_on:
      - web-server
  dashboard:
    image: app-tunnel
    entrypoint: lt --port 9869 --subdomain 'dashboard-ifiver'
    restart: unless-stopped
    network_mode: host
  fireedge:
    image: app-tunnel
    entrypoint: lt --port 2616 --subdomain 'fireedge-ifiver'
    restart: unless-stopped
    network_mode: host
  backend:
    image: ngrok/ngrok
    entrypoint: http 8080
    restart: unless-stopped
    network_mode: host
    expose:
      - 4040
    depends_on:
      - api-server